# Generated by Django 3.0.7 on 2020-10-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Squirrel',
        ),
    ]
